// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_stat.proto

package io.activej.dataflow.proto;

public final class NodeStatProto {
  private NodeStatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeStatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataflow.NodeStat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     * @return Whether the binary field is set.
     */
    boolean hasBinary();
    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     * @return The binary.
     */
    io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getBinary();
    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     */
    io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder getBinaryOrBuilder();

    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     * @return Whether the test field is set.
     */
    boolean hasTest();
    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     * @return The test.
     */
    io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getTest();
    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     */
    io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder getTestOrBuilder();

    public io.activej.dataflow.proto.NodeStatProto.NodeStat.NodeStatCase getNodeStatCase();
  }
  /**
   * Protobuf type {@code dataflow.NodeStat}
   */
  public static final class NodeStat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataflow.NodeStat)
      NodeStatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeStat.newBuilder() to construct.
    private NodeStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeStat() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NodeStat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeStat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder subBuilder = null;
              if (nodeStatCase_ == 1) {
                subBuilder = ((io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_).toBuilder();
              }
              nodeStat_ =
                  input.readMessage(io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_);
                nodeStat_ = subBuilder.buildPartial();
              }
              nodeStatCase_ = 1;
              break;
            }
            case 18: {
              io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder subBuilder = null;
              if (nodeStatCase_ == 2) {
                subBuilder = ((io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_).toBuilder();
              }
              nodeStat_ =
                  input.readMessage(io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_);
                nodeStat_ = subBuilder.buildPartial();
              }
              nodeStatCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.activej.dataflow.proto.NodeStatProto.NodeStat.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Builder.class);
    }

    public interface BinaryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dataflow.NodeStat.Binary)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 bytes = 1;</code>
       * @return The bytes.
       */
      long getBytes();
    }
    /**
     * Protobuf type {@code dataflow.NodeStat.Binary}
     */
    public static final class Binary extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dataflow.NodeStat.Binary)
        BinaryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Binary.newBuilder() to construct.
      private Binary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Binary() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Binary();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Binary(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                bytes_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Binary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Binary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder.class);
      }

      public static final int BYTES_FIELD_NUMBER = 1;
      private long bytes_;
      /**
       * <code>int64 bytes = 1;</code>
       * @return The bytes.
       */
      @java.lang.Override
      public long getBytes() {
        return bytes_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (bytes_ != 0L) {
          output.writeInt64(1, bytes_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (bytes_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, bytes_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary)) {
          return super.equals(obj);
        }
        io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary other = (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) obj;

        if (getBytes()
            != other.getBytes()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BYTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBytes());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dataflow.NodeStat.Binary}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dataflow.NodeStat.Binary)
          io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Binary_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Binary_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder.class);
        }

        // Construct using io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bytes_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Binary_descriptor;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getDefaultInstanceForType() {
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary build() {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary buildPartial() {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary result = new io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary(this);
          result.bytes_ = bytes_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) {
            return mergeFrom((io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary other) {
          if (other == io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance()) return this;
          if (other.getBytes() != 0L) {
            setBytes(other.getBytes());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long bytes_ ;
        /**
         * <code>int64 bytes = 1;</code>
         * @return The bytes.
         */
        @java.lang.Override
        public long getBytes() {
          return bytes_;
        }
        /**
         * <code>int64 bytes = 1;</code>
         * @param value The bytes to set.
         * @return This builder for chaining.
         */
        public Builder setBytes(long value) {
          
          bytes_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 bytes = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearBytes() {
          
          bytes_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dataflow.NodeStat.Binary)
      }

      // @@protoc_insertion_point(class_scope:dataflow.NodeStat.Binary)
      private static final io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary();
      }

      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Binary>
          PARSER = new com.google.protobuf.AbstractParser<Binary>() {
        @java.lang.Override
        public Binary parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Binary(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Binary> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Binary> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface TestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dataflow.NodeStat.Test)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 node_index = 1;</code>
       * @return The nodeIndex.
       */
      int getNodeIndex();
    }
    /**
     * Protobuf type {@code dataflow.NodeStat.Test}
     */
    public static final class Test extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dataflow.NodeStat.Test)
        TestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Test.newBuilder() to construct.
      private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Test() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Test();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Test(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                nodeIndex_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Test_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder.class);
      }

      public static final int NODE_INDEX_FIELD_NUMBER = 1;
      private int nodeIndex_;
      /**
       * <code>int32 node_index = 1;</code>
       * @return The nodeIndex.
       */
      @java.lang.Override
      public int getNodeIndex() {
        return nodeIndex_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (nodeIndex_ != 0) {
          output.writeInt32(1, nodeIndex_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (nodeIndex_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, nodeIndex_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat.Test)) {
          return super.equals(obj);
        }
        io.activej.dataflow.proto.NodeStatProto.NodeStat.Test other = (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) obj;

        if (getNodeIndex()
            != other.getNodeIndex()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NODE_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getNodeIndex();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.activej.dataflow.proto.NodeStatProto.NodeStat.Test prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dataflow.NodeStat.Test}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dataflow.NodeStat.Test)
          io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Test_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Test_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder.class);
        }

        // Construct using io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          nodeIndex_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_Test_descriptor;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getDefaultInstanceForType() {
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test build() {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test buildPartial() {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test result = new io.activej.dataflow.proto.NodeStatProto.NodeStat.Test(this);
          result.nodeIndex_ = nodeIndex_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) {
            return mergeFrom((io.activej.dataflow.proto.NodeStatProto.NodeStat.Test)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.activej.dataflow.proto.NodeStatProto.NodeStat.Test other) {
          if (other == io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance()) return this;
          if (other.getNodeIndex() != 0) {
            setNodeIndex(other.getNodeIndex());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int nodeIndex_ ;
        /**
         * <code>int32 node_index = 1;</code>
         * @return The nodeIndex.
         */
        @java.lang.Override
        public int getNodeIndex() {
          return nodeIndex_;
        }
        /**
         * <code>int32 node_index = 1;</code>
         * @param value The nodeIndex to set.
         * @return This builder for chaining.
         */
        public Builder setNodeIndex(int value) {
          
          nodeIndex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 node_index = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNodeIndex() {
          
          nodeIndex_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dataflow.NodeStat.Test)
      }

      // @@protoc_insertion_point(class_scope:dataflow.NodeStat.Test)
      private static final io.activej.dataflow.proto.NodeStatProto.NodeStat.Test DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.activej.dataflow.proto.NodeStatProto.NodeStat.Test();
      }

      public static io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Test>
          PARSER = new com.google.protobuf.AbstractParser<Test>() {
        @java.lang.Override
        public Test parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Test> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Test> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int nodeStatCase_ = 0;
    private java.lang.Object nodeStat_;
    public enum NodeStatCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BINARY(1),
      TEST(2),
      NODESTAT_NOT_SET(0);
      private final int value;
      private NodeStatCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NodeStatCase valueOf(int value) {
        return forNumber(value);
      }

      public static NodeStatCase forNumber(int value) {
        switch (value) {
          case 1: return BINARY;
          case 2: return TEST;
          case 0: return NODESTAT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public NodeStatCase
    getNodeStatCase() {
      return NodeStatCase.forNumber(
          nodeStatCase_);
    }

    public static final int BINARY_FIELD_NUMBER = 1;
    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     * @return Whether the binary field is set.
     */
    @java.lang.Override
    public boolean hasBinary() {
      return nodeStatCase_ == 1;
    }
    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     * @return The binary.
     */
    @java.lang.Override
    public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getBinary() {
      if (nodeStatCase_ == 1) {
         return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_;
      }
      return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
    }
    /**
     * <code>.dataflow.NodeStat.Binary binary = 1;</code>
     */
    @java.lang.Override
    public io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder getBinaryOrBuilder() {
      if (nodeStatCase_ == 1) {
         return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_;
      }
      return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
    }

    public static final int TEST_FIELD_NUMBER = 2;
    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     * @return Whether the test field is set.
     */
    @java.lang.Override
    public boolean hasTest() {
      return nodeStatCase_ == 2;
    }
    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     * @return The test.
     */
    @java.lang.Override
    public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getTest() {
      if (nodeStatCase_ == 2) {
         return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_;
      }
      return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
    }
    /**
     * <code>.dataflow.NodeStat.Test test = 2;</code>
     */
    @java.lang.Override
    public io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder getTestOrBuilder() {
      if (nodeStatCase_ == 2) {
         return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_;
      }
      return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeStatCase_ == 1) {
        output.writeMessage(1, (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_);
      }
      if (nodeStatCase_ == 2) {
        output.writeMessage(2, (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeStatCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_);
      }
      if (nodeStatCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat)) {
        return super.equals(obj);
      }
      io.activej.dataflow.proto.NodeStatProto.NodeStat other = (io.activej.dataflow.proto.NodeStatProto.NodeStat) obj;

      if (!getNodeStatCase().equals(other.getNodeStatCase())) return false;
      switch (nodeStatCase_) {
        case 1:
          if (!getBinary()
              .equals(other.getBinary())) return false;
          break;
        case 2:
          if (!getTest()
              .equals(other.getTest())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (nodeStatCase_) {
        case 1:
          hash = (37 * hash) + BINARY_FIELD_NUMBER;
          hash = (53 * hash) + getBinary().hashCode();
          break;
        case 2:
          hash = (37 * hash) + TEST_FIELD_NUMBER;
          hash = (53 * hash) + getTest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.NodeStatProto.NodeStat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.activej.dataflow.proto.NodeStatProto.NodeStat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataflow.NodeStat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataflow.NodeStat)
        io.activej.dataflow.proto.NodeStatProto.NodeStatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.NodeStatProto.NodeStat.class, io.activej.dataflow.proto.NodeStatProto.NodeStat.Builder.class);
      }

      // Construct using io.activej.dataflow.proto.NodeStatProto.NodeStat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeStatCase_ = 0;
        nodeStat_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.activej.dataflow.proto.NodeStatProto.internal_static_dataflow_NodeStat_descriptor;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat getDefaultInstanceForType() {
        return io.activej.dataflow.proto.NodeStatProto.NodeStat.getDefaultInstance();
      }

      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat build() {
        io.activej.dataflow.proto.NodeStatProto.NodeStat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat buildPartial() {
        io.activej.dataflow.proto.NodeStatProto.NodeStat result = new io.activej.dataflow.proto.NodeStatProto.NodeStat(this);
        if (nodeStatCase_ == 1) {
          if (binaryBuilder_ == null) {
            result.nodeStat_ = nodeStat_;
          } else {
            result.nodeStat_ = binaryBuilder_.build();
          }
        }
        if (nodeStatCase_ == 2) {
          if (testBuilder_ == null) {
            result.nodeStat_ = nodeStat_;
          } else {
            result.nodeStat_ = testBuilder_.build();
          }
        }
        result.nodeStatCase_ = nodeStatCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.activej.dataflow.proto.NodeStatProto.NodeStat) {
          return mergeFrom((io.activej.dataflow.proto.NodeStatProto.NodeStat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.activej.dataflow.proto.NodeStatProto.NodeStat other) {
        if (other == io.activej.dataflow.proto.NodeStatProto.NodeStat.getDefaultInstance()) return this;
        switch (other.getNodeStatCase()) {
          case BINARY: {
            mergeBinary(other.getBinary());
            break;
          }
          case TEST: {
            mergeTest(other.getTest());
            break;
          }
          case NODESTAT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.activej.dataflow.proto.NodeStatProto.NodeStat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.activej.dataflow.proto.NodeStatProto.NodeStat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int nodeStatCase_ = 0;
      private java.lang.Object nodeStat_;
      public NodeStatCase
          getNodeStatCase() {
        return NodeStatCase.forNumber(
            nodeStatCase_);
      }

      public Builder clearNodeStat() {
        nodeStatCase_ = 0;
        nodeStat_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary, io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder> binaryBuilder_;
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       * @return Whether the binary field is set.
       */
      @java.lang.Override
      public boolean hasBinary() {
        return nodeStatCase_ == 1;
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       * @return The binary.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary getBinary() {
        if (binaryBuilder_ == null) {
          if (nodeStatCase_ == 1) {
            return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_;
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
        } else {
          if (nodeStatCase_ == 1) {
            return binaryBuilder_.getMessage();
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      public Builder setBinary(io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary value) {
        if (binaryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nodeStat_ = value;
          onChanged();
        } else {
          binaryBuilder_.setMessage(value);
        }
        nodeStatCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      public Builder setBinary(
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder builderForValue) {
        if (binaryBuilder_ == null) {
          nodeStat_ = builderForValue.build();
          onChanged();
        } else {
          binaryBuilder_.setMessage(builderForValue.build());
        }
        nodeStatCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      public Builder mergeBinary(io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary value) {
        if (binaryBuilder_ == null) {
          if (nodeStatCase_ == 1 &&
              nodeStat_ != io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance()) {
            nodeStat_ = io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.newBuilder((io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_)
                .mergeFrom(value).buildPartial();
          } else {
            nodeStat_ = value;
          }
          onChanged();
        } else {
          if (nodeStatCase_ == 1) {
            binaryBuilder_.mergeFrom(value);
          }
          binaryBuilder_.setMessage(value);
        }
        nodeStatCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      public Builder clearBinary() {
        if (binaryBuilder_ == null) {
          if (nodeStatCase_ == 1) {
            nodeStatCase_ = 0;
            nodeStat_ = null;
            onChanged();
          }
        } else {
          if (nodeStatCase_ == 1) {
            nodeStatCase_ = 0;
            nodeStat_ = null;
          }
          binaryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder getBinaryBuilder() {
        return getBinaryFieldBuilder().getBuilder();
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder getBinaryOrBuilder() {
        if ((nodeStatCase_ == 1) && (binaryBuilder_ != null)) {
          return binaryBuilder_.getMessageOrBuilder();
        } else {
          if (nodeStatCase_ == 1) {
            return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_;
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.NodeStat.Binary binary = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary, io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder> 
          getBinaryFieldBuilder() {
        if (binaryBuilder_ == null) {
          if (!(nodeStatCase_ == 1)) {
            nodeStat_ = io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.getDefaultInstance();
          }
          binaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary, io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.BinaryOrBuilder>(
                  (io.activej.dataflow.proto.NodeStatProto.NodeStat.Binary) nodeStat_,
                  getParentForChildren(),
                  isClean());
          nodeStat_ = null;
        }
        nodeStatCase_ = 1;
        onChanged();;
        return binaryBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test, io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder> testBuilder_;
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       * @return Whether the test field is set.
       */
      @java.lang.Override
      public boolean hasTest() {
        return nodeStatCase_ == 2;
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       * @return The test.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test getTest() {
        if (testBuilder_ == null) {
          if (nodeStatCase_ == 2) {
            return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_;
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
        } else {
          if (nodeStatCase_ == 2) {
            return testBuilder_.getMessage();
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      public Builder setTest(io.activej.dataflow.proto.NodeStatProto.NodeStat.Test value) {
        if (testBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nodeStat_ = value;
          onChanged();
        } else {
          testBuilder_.setMessage(value);
        }
        nodeStatCase_ = 2;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      public Builder setTest(
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder builderForValue) {
        if (testBuilder_ == null) {
          nodeStat_ = builderForValue.build();
          onChanged();
        } else {
          testBuilder_.setMessage(builderForValue.build());
        }
        nodeStatCase_ = 2;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      public Builder mergeTest(io.activej.dataflow.proto.NodeStatProto.NodeStat.Test value) {
        if (testBuilder_ == null) {
          if (nodeStatCase_ == 2 &&
              nodeStat_ != io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance()) {
            nodeStat_ = io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.newBuilder((io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_)
                .mergeFrom(value).buildPartial();
          } else {
            nodeStat_ = value;
          }
          onChanged();
        } else {
          if (nodeStatCase_ == 2) {
            testBuilder_.mergeFrom(value);
          }
          testBuilder_.setMessage(value);
        }
        nodeStatCase_ = 2;
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      public Builder clearTest() {
        if (testBuilder_ == null) {
          if (nodeStatCase_ == 2) {
            nodeStatCase_ = 0;
            nodeStat_ = null;
            onChanged();
          }
        } else {
          if (nodeStatCase_ == 2) {
            nodeStatCase_ = 0;
            nodeStat_ = null;
          }
          testBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder getTestBuilder() {
        return getTestFieldBuilder().getBuilder();
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder getTestOrBuilder() {
        if ((nodeStatCase_ == 2) && (testBuilder_ != null)) {
          return testBuilder_.getMessageOrBuilder();
        } else {
          if (nodeStatCase_ == 2) {
            return (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_;
          }
          return io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.NodeStat.Test test = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.NodeStatProto.NodeStat.Test, io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder> 
          getTestFieldBuilder() {
        if (testBuilder_ == null) {
          if (!(nodeStatCase_ == 2)) {
            nodeStat_ = io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.getDefaultInstance();
          }
          testBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.activej.dataflow.proto.NodeStatProto.NodeStat.Test, io.activej.dataflow.proto.NodeStatProto.NodeStat.Test.Builder, io.activej.dataflow.proto.NodeStatProto.NodeStat.TestOrBuilder>(
                  (io.activej.dataflow.proto.NodeStatProto.NodeStat.Test) nodeStat_,
                  getParentForChildren(),
                  isClean());
          nodeStat_ = null;
        }
        nodeStatCase_ = 2;
        onChanged();;
        return testBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataflow.NodeStat)
    }

    // @@protoc_insertion_point(class_scope:dataflow.NodeStat)
    private static final io.activej.dataflow.proto.NodeStatProto.NodeStat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.activej.dataflow.proto.NodeStatProto.NodeStat();
    }

    public static io.activej.dataflow.proto.NodeStatProto.NodeStat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeStat>
        PARSER = new com.google.protobuf.AbstractParser<NodeStat>() {
      @java.lang.Override
      public NodeStat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeStat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeStat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeStat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.activej.dataflow.proto.NodeStatProto.NodeStat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_NodeStat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_NodeStat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_NodeStat_Binary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_NodeStat_Binary_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_NodeStat_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_NodeStat_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017node_stat.proto\022\010dataflow\"\242\001\n\010NodeStat" +
      "\022+\n\006binary\030\001 \001(\0132\031.dataflow.NodeStat.Bin" +
      "aryH\000\022\'\n\004test\030\002 \001(\0132\027.dataflow.NodeStat." +
      "TestH\000\032\027\n\006Binary\022\r\n\005bytes\030\001 \001(\003\032\032\n\004Test\022" +
      "\022\n\nnode_index\030\001 \001(\005B\013\n\tnode_statB,\n\031io.a" +
      "ctivej.dataflow.protoB\rNodeStatProtoP\000b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dataflow_NodeStat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataflow_NodeStat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_NodeStat_descriptor,
        new java.lang.String[] { "Binary", "Test", "NodeStat", });
    internal_static_dataflow_NodeStat_Binary_descriptor =
      internal_static_dataflow_NodeStat_descriptor.getNestedTypes().get(0);
    internal_static_dataflow_NodeStat_Binary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_NodeStat_Binary_descriptor,
        new java.lang.String[] { "Bytes", });
    internal_static_dataflow_NodeStat_Test_descriptor =
      internal_static_dataflow_NodeStat_descriptor.getNestedTypes().get(1);
    internal_static_dataflow_NodeStat_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_NodeStat_Test_descriptor,
        new java.lang.String[] { "NodeIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
