/*
 * This file is generated by jOOQ.
 */
package advanced.jooq.model;


import advanced.jooq.model.tables.NewUsers;
import advanced.jooq.model.tables.Users;
import advanced.jooq.model.tables.records.NewUsersRecord;
import advanced.jooq.model.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<NewUsersRecord> CONSTRAINT_F = Internal.createUniqueKey(NewUsers.NEW_USERS, DSL.name("CONSTRAINT_F"), new TableField[] { NewUsers.NEW_USERS.ID }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_6 = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_6"), new TableField[] { Users.USERS.ID }, true);
}
