/*
 * This file is generated by jOOQ.
 */
package advanced.jooq.model;


import advanced.jooq.model.tables.NewUsers;
import advanced.jooq.model.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>new_users</code>.
     */
    public static final NewUsers NEW_USERS = NewUsers.NEW_USERS;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
