/*
 * This file is generated by jOOQ.
 */
package advanced.jooq.model.tables;


import advanced.jooq.model.DefaultSchema;
import advanced.jooq.model.Keys;
import advanced.jooq.model.tables.records.NewUserRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NewUser extends TableImpl<NewUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>new_user</code>
     */
    public static final NewUser NEW_USER = new NewUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewUserRecord> getRecordType() {
        return NewUserRecord.class;
    }

    /**
     * The column <code>new_user.id</code>.
     */
    public final TableField<NewUserRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>new_user.first_name</code>.
     */
    public final TableField<NewUserRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>new_user.last_name</code>.
     */
    public final TableField<NewUserRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    private NewUser(Name alias, Table<NewUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NewUser(Name alias, Table<NewUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>new_user</code> table reference
     */
    public NewUser(String alias) {
        this(DSL.name(alias), NEW_USER);
    }

    /**
     * Create an aliased <code>new_user</code> table reference
     */
    public NewUser(Name alias) {
        this(alias, NEW_USER);
    }

    /**
     * Create a <code>new_user</code> table reference
     */
    public NewUser() {
        this(DSL.name("new_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<NewUserRecord, Integer> getIdentity() {
        return (Identity<NewUserRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NewUserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    @Override
    public NewUser as(String alias) {
        return new NewUser(DSL.name(alias), this);
    }

    @Override
    public NewUser as(Name alias) {
        return new NewUser(alias, this);
    }

    @Override
    public NewUser as(Table<?> alias) {
        return new NewUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NewUser rename(String name) {
        return new NewUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewUser rename(Name name) {
        return new NewUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewUser rename(Table<?> name) {
        return new NewUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser where(Condition condition) {
        return new NewUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
