// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcite/calcite_node.proto

package io.activej.dataflow.proto.calcite;

public final class CalciteNodeProto {
  private CalciteNodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalciteNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataflow.calcite.CalciteNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     * @return Whether the filterableSupplierOfId field is set.
     */
    boolean hasFilterableSupplierOfId();
    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     * @return The filterableSupplierOfId.
     */
    io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getFilterableSupplierOfId();
    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     */
    io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder getFilterableSupplierOfIdOrBuilder();

    public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.NodeCase getNodeCase();
  }
  /**
   * Protobuf type {@code dataflow.calcite.CalciteNode}
   */
  public static final class CalciteNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataflow.calcite.CalciteNode)
      CalciteNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalciteNode.newBuilder() to construct.
    private CalciteNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalciteNode() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalciteNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalciteNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder subBuilder = null;
              if (nodeCase_ == 1) {
                subBuilder = ((io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_).toBuilder();
              }
              node_ =
                  input.readMessage(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_);
                node_ = subBuilder.buildPartial();
              }
              nodeCase_ = 1;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.class, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.Builder.class);
    }

    public interface FilterableSupplierOfIdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dataflow.calcite.CalciteNode.FilterableSupplierOfId)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      int getIndex();

      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      java.lang.String getId();
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       * @return Whether the predicate field is set.
       */
      boolean hasPredicate();
      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       * @return The predicate.
       */
      io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate getPredicate();
      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       */
      io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder getPredicateOrBuilder();

      /**
       * <code>int32 partition_index = 4;</code>
       * @return The partitionIndex.
       */
      int getPartitionIndex();

      /**
       * <code>int32 max_partitions = 5;</code>
       * @return The maxPartitions.
       */
      int getMaxPartitions();

      /**
       * <code>.dataflow.StreamId output = 6;</code>
       * @return Whether the output field is set.
       */
      boolean hasOutput();
      /**
       * <code>.dataflow.StreamId output = 6;</code>
       * @return The output.
       */
      io.activej.dataflow.proto.StreamIdProto.StreamId getOutput();
      /**
       * <code>.dataflow.StreamId output = 6;</code>
       */
      io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder getOutputOrBuilder();
    }
    /**
     * Protobuf type {@code dataflow.calcite.CalciteNode.FilterableSupplierOfId}
     */
    public static final class FilterableSupplierOfId extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dataflow.calcite.CalciteNode.FilterableSupplierOfId)
        FilterableSupplierOfIdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use FilterableSupplierOfId.newBuilder() to construct.
      private FilterableSupplierOfId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private FilterableSupplierOfId() {
        id_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new FilterableSupplierOfId();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private FilterableSupplierOfId(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                index_ = input.readInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
              case 26: {
                io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder subBuilder = null;
                if (predicate_ != null) {
                  subBuilder = predicate_.toBuilder();
                }
                predicate_ = input.readMessage(io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(predicate_);
                  predicate_ = subBuilder.buildPartial();
                }

                break;
              }
              case 32: {

                partitionIndex_ = input.readInt32();
                break;
              }
              case 40: {

                maxPartitions_ = input.readInt32();
                break;
              }
              case 50: {
                io.activej.dataflow.proto.StreamIdProto.StreamId.Builder subBuilder = null;
                if (output_ != null) {
                  subBuilder = output_.toBuilder();
                }
                output_ = input.readMessage(io.activej.dataflow.proto.StreamIdProto.StreamId.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(output_);
                  output_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.class, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder.class);
      }

      public static final int INDEX_FIELD_NUMBER = 1;
      private int index_;
      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }

      public static final int ID_FIELD_NUMBER = 2;
      private volatile java.lang.Object id_;
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PREDICATE_FIELD_NUMBER = 3;
      private io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate predicate_;
      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       * @return Whether the predicate field is set.
       */
      @java.lang.Override
      public boolean hasPredicate() {
        return predicate_ != null;
      }
      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       * @return The predicate.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate getPredicate() {
        return predicate_ == null ? io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.getDefaultInstance() : predicate_;
      }
      /**
       * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder getPredicateOrBuilder() {
        return getPredicate();
      }

      public static final int PARTITION_INDEX_FIELD_NUMBER = 4;
      private int partitionIndex_;
      /**
       * <code>int32 partition_index = 4;</code>
       * @return The partitionIndex.
       */
      @java.lang.Override
      public int getPartitionIndex() {
        return partitionIndex_;
      }

      public static final int MAX_PARTITIONS_FIELD_NUMBER = 5;
      private int maxPartitions_;
      /**
       * <code>int32 max_partitions = 5;</code>
       * @return The maxPartitions.
       */
      @java.lang.Override
      public int getMaxPartitions() {
        return maxPartitions_;
      }

      public static final int OUTPUT_FIELD_NUMBER = 6;
      private io.activej.dataflow.proto.StreamIdProto.StreamId output_;
      /**
       * <code>.dataflow.StreamId output = 6;</code>
       * @return Whether the output field is set.
       */
      @java.lang.Override
      public boolean hasOutput() {
        return output_ != null;
      }
      /**
       * <code>.dataflow.StreamId output = 6;</code>
       * @return The output.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.StreamIdProto.StreamId getOutput() {
        return output_ == null ? io.activej.dataflow.proto.StreamIdProto.StreamId.getDefaultInstance() : output_;
      }
      /**
       * <code>.dataflow.StreamId output = 6;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder getOutputOrBuilder() {
        return getOutput();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (index_ != 0) {
          output.writeInt32(1, index_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
        }
        if (predicate_ != null) {
          output.writeMessage(3, getPredicate());
        }
        if (partitionIndex_ != 0) {
          output.writeInt32(4, partitionIndex_);
        }
        if (maxPartitions_ != 0) {
          output.writeInt32(5, maxPartitions_);
        }
        if (output_ != null) {
          output.writeMessage(6, getOutput());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (index_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, index_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
        }
        if (predicate_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, getPredicate());
        }
        if (partitionIndex_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, partitionIndex_);
        }
        if (maxPartitions_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, maxPartitions_);
        }
        if (output_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, getOutput());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId)) {
          return super.equals(obj);
        }
        io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId other = (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) obj;

        if (getIndex()
            != other.getIndex()) return false;
        if (!getId()
            .equals(other.getId())) return false;
        if (hasPredicate() != other.hasPredicate()) return false;
        if (hasPredicate()) {
          if (!getPredicate()
              .equals(other.getPredicate())) return false;
        }
        if (getPartitionIndex()
            != other.getPartitionIndex()) return false;
        if (getMaxPartitions()
            != other.getMaxPartitions()) return false;
        if (hasOutput() != other.hasOutput()) return false;
        if (hasOutput()) {
          if (!getOutput()
              .equals(other.getOutput())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        if (hasPredicate()) {
          hash = (37 * hash) + PREDICATE_FIELD_NUMBER;
          hash = (53 * hash) + getPredicate().hashCode();
        }
        hash = (37 * hash) + PARTITION_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getPartitionIndex();
        hash = (37 * hash) + MAX_PARTITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getMaxPartitions();
        if (hasOutput()) {
          hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
          hash = (53 * hash) + getOutput().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dataflow.calcite.CalciteNode.FilterableSupplierOfId}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dataflow.calcite.CalciteNode.FilterableSupplierOfId)
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.class, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder.class);
        }

        // Construct using io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          index_ = 0;

          id_ = "";

          if (predicateBuilder_ == null) {
            predicate_ = null;
          } else {
            predicate_ = null;
            predicateBuilder_ = null;
          }
          partitionIndex_ = 0;

          maxPartitions_ = 0;

          if (outputBuilder_ == null) {
            output_ = null;
          } else {
            output_ = null;
            outputBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getDefaultInstanceForType() {
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId build() {
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId buildPartial() {
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId result = new io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId(this);
          result.index_ = index_;
          result.id_ = id_;
          if (predicateBuilder_ == null) {
            result.predicate_ = predicate_;
          } else {
            result.predicate_ = predicateBuilder_.build();
          }
          result.partitionIndex_ = partitionIndex_;
          result.maxPartitions_ = maxPartitions_;
          if (outputBuilder_ == null) {
            result.output_ = output_;
          } else {
            result.output_ = outputBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) {
            return mergeFrom((io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId other) {
          if (other == io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance()) return this;
          if (other.getIndex() != 0) {
            setIndex(other.getIndex());
          }
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            onChanged();
          }
          if (other.hasPredicate()) {
            mergePredicate(other.getPredicate());
          }
          if (other.getPartitionIndex() != 0) {
            setPartitionIndex(other.getPartitionIndex());
          }
          if (other.getMaxPartitions() != 0) {
            setMaxPartitions(other.getMaxPartitions());
          }
          if (other.hasOutput()) {
            mergeOutput(other.getOutput());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int index_ ;
        /**
         * <code>int32 index = 1;</code>
         * @return The index.
         */
        @java.lang.Override
        public int getIndex() {
          return index_;
        }
        /**
         * <code>int32 index = 1;</code>
         * @param value The index to set.
         * @return This builder for chaining.
         */
        public Builder setIndex(int value) {
          
          index_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 index = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearIndex() {
          
          index_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object id_ = "";
        /**
         * <code>string id = 2;</code>
         * @return The id.
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string id = 2;</code>
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string id = 2;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string id = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>string id = 2;</code>
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          id_ = value;
          onChanged();
          return this;
        }

        private io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate predicate_;
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder> predicateBuilder_;
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         * @return Whether the predicate field is set.
         */
        public boolean hasPredicate() {
          return predicateBuilder_ != null || predicate_ != null;
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         * @return The predicate.
         */
        public io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate getPredicate() {
          if (predicateBuilder_ == null) {
            return predicate_ == null ? io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.getDefaultInstance() : predicate_;
          } else {
            return predicateBuilder_.getMessage();
          }
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public Builder setPredicate(io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate value) {
          if (predicateBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            predicate_ = value;
            onChanged();
          } else {
            predicateBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public Builder setPredicate(
            io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder builderForValue) {
          if (predicateBuilder_ == null) {
            predicate_ = builderForValue.build();
            onChanged();
          } else {
            predicateBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public Builder mergePredicate(io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate value) {
          if (predicateBuilder_ == null) {
            if (predicate_ != null) {
              predicate_ =
                io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.newBuilder(predicate_).mergeFrom(value).buildPartial();
            } else {
              predicate_ = value;
            }
            onChanged();
          } else {
            predicateBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public Builder clearPredicate() {
          if (predicateBuilder_ == null) {
            predicate_ = null;
            onChanged();
          } else {
            predicate_ = null;
            predicateBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder getPredicateBuilder() {
          
          onChanged();
          return getPredicateFieldBuilder().getBuilder();
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        public io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder getPredicateOrBuilder() {
          if (predicateBuilder_ != null) {
            return predicateBuilder_.getMessageOrBuilder();
          } else {
            return predicate_ == null ?
                io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.getDefaultInstance() : predicate_;
          }
        }
        /**
         * <code>.dataflow.calcite.WherePredicate predicate = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder> 
            getPredicateFieldBuilder() {
          if (predicateBuilder_ == null) {
            predicateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicate.Builder, io.activej.dataflow.proto.calcite.WherePredicateProto.WherePredicateOrBuilder>(
                    getPredicate(),
                    getParentForChildren(),
                    isClean());
            predicate_ = null;
          }
          return predicateBuilder_;
        }

        private int partitionIndex_ ;
        /**
         * <code>int32 partition_index = 4;</code>
         * @return The partitionIndex.
         */
        @java.lang.Override
        public int getPartitionIndex() {
          return partitionIndex_;
        }
        /**
         * <code>int32 partition_index = 4;</code>
         * @param value The partitionIndex to set.
         * @return This builder for chaining.
         */
        public Builder setPartitionIndex(int value) {
          
          partitionIndex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 partition_index = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearPartitionIndex() {
          
          partitionIndex_ = 0;
          onChanged();
          return this;
        }

        private int maxPartitions_ ;
        /**
         * <code>int32 max_partitions = 5;</code>
         * @return The maxPartitions.
         */
        @java.lang.Override
        public int getMaxPartitions() {
          return maxPartitions_;
        }
        /**
         * <code>int32 max_partitions = 5;</code>
         * @param value The maxPartitions to set.
         * @return This builder for chaining.
         */
        public Builder setMaxPartitions(int value) {
          
          maxPartitions_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 max_partitions = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearMaxPartitions() {
          
          maxPartitions_ = 0;
          onChanged();
          return this;
        }

        private io.activej.dataflow.proto.StreamIdProto.StreamId output_;
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.StreamIdProto.StreamId, io.activej.dataflow.proto.StreamIdProto.StreamId.Builder, io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder> outputBuilder_;
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         * @return Whether the output field is set.
         */
        public boolean hasOutput() {
          return outputBuilder_ != null || output_ != null;
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         * @return The output.
         */
        public io.activej.dataflow.proto.StreamIdProto.StreamId getOutput() {
          if (outputBuilder_ == null) {
            return output_ == null ? io.activej.dataflow.proto.StreamIdProto.StreamId.getDefaultInstance() : output_;
          } else {
            return outputBuilder_.getMessage();
          }
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public Builder setOutput(io.activej.dataflow.proto.StreamIdProto.StreamId value) {
          if (outputBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            output_ = value;
            onChanged();
          } else {
            outputBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public Builder setOutput(
            io.activej.dataflow.proto.StreamIdProto.StreamId.Builder builderForValue) {
          if (outputBuilder_ == null) {
            output_ = builderForValue.build();
            onChanged();
          } else {
            outputBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public Builder mergeOutput(io.activej.dataflow.proto.StreamIdProto.StreamId value) {
          if (outputBuilder_ == null) {
            if (output_ != null) {
              output_ =
                io.activej.dataflow.proto.StreamIdProto.StreamId.newBuilder(output_).mergeFrom(value).buildPartial();
            } else {
              output_ = value;
            }
            onChanged();
          } else {
            outputBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public Builder clearOutput() {
          if (outputBuilder_ == null) {
            output_ = null;
            onChanged();
          } else {
            output_ = null;
            outputBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public io.activej.dataflow.proto.StreamIdProto.StreamId.Builder getOutputBuilder() {
          
          onChanged();
          return getOutputFieldBuilder().getBuilder();
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        public io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder getOutputOrBuilder() {
          if (outputBuilder_ != null) {
            return outputBuilder_.getMessageOrBuilder();
          } else {
            return output_ == null ?
                io.activej.dataflow.proto.StreamIdProto.StreamId.getDefaultInstance() : output_;
          }
        }
        /**
         * <code>.dataflow.StreamId output = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.StreamIdProto.StreamId, io.activej.dataflow.proto.StreamIdProto.StreamId.Builder, io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder> 
            getOutputFieldBuilder() {
          if (outputBuilder_ == null) {
            outputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                io.activej.dataflow.proto.StreamIdProto.StreamId, io.activej.dataflow.proto.StreamIdProto.StreamId.Builder, io.activej.dataflow.proto.StreamIdProto.StreamIdOrBuilder>(
                    getOutput(),
                    getParentForChildren(),
                    isClean());
            output_ = null;
          }
          return outputBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dataflow.calcite.CalciteNode.FilterableSupplierOfId)
      }

      // @@protoc_insertion_point(class_scope:dataflow.calcite.CalciteNode.FilterableSupplierOfId)
      private static final io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId();
      }

      public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<FilterableSupplierOfId>
          PARSER = new com.google.protobuf.AbstractParser<FilterableSupplierOfId>() {
        @java.lang.Override
        public FilterableSupplierOfId parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FilterableSupplierOfId(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<FilterableSupplierOfId> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<FilterableSupplierOfId> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int nodeCase_ = 0;
    private java.lang.Object node_;
    public enum NodeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FILTERABLE_SUPPLIER_OF_ID(1),
      NODE_NOT_SET(0);
      private final int value;
      private NodeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NodeCase valueOf(int value) {
        return forNumber(value);
      }

      public static NodeCase forNumber(int value) {
        switch (value) {
          case 1: return FILTERABLE_SUPPLIER_OF_ID;
          case 0: return NODE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public NodeCase
    getNodeCase() {
      return NodeCase.forNumber(
          nodeCase_);
    }

    public static final int FILTERABLE_SUPPLIER_OF_ID_FIELD_NUMBER = 1;
    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     * @return Whether the filterableSupplierOfId field is set.
     */
    @java.lang.Override
    public boolean hasFilterableSupplierOfId() {
      return nodeCase_ == 1;
    }
    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     * @return The filterableSupplierOfId.
     */
    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getFilterableSupplierOfId() {
      if (nodeCase_ == 1) {
         return (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_;
      }
      return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
    }
    /**
     * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
     */
    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder getFilterableSupplierOfIdOrBuilder() {
      if (nodeCase_ == 1) {
         return (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_;
      }
      return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeCase_ == 1) {
        output.writeMessage(1, (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode)) {
        return super.equals(obj);
      }
      io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode other = (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode) obj;

      if (!getNodeCase().equals(other.getNodeCase())) return false;
      switch (nodeCase_) {
        case 1:
          if (!getFilterableSupplierOfId()
              .equals(other.getFilterableSupplierOfId())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (nodeCase_) {
        case 1:
          hash = (37 * hash) + FILTERABLE_SUPPLIER_OF_ID_FIELD_NUMBER;
          hash = (53 * hash) + getFilterableSupplierOfId().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataflow.calcite.CalciteNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataflow.calcite.CalciteNode)
        io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.class, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.Builder.class);
      }

      // Construct using io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeCase_ = 0;
        node_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.internal_static_dataflow_calcite_CalciteNode_descriptor;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode getDefaultInstanceForType() {
        return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.getDefaultInstance();
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode build() {
        io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode buildPartial() {
        io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode result = new io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode(this);
        if (nodeCase_ == 1) {
          if (filterableSupplierOfIdBuilder_ == null) {
            result.node_ = node_;
          } else {
            result.node_ = filterableSupplierOfIdBuilder_.build();
          }
        }
        result.nodeCase_ = nodeCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode) {
          return mergeFrom((io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode other) {
        if (other == io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.getDefaultInstance()) return this;
        switch (other.getNodeCase()) {
          case FILTERABLE_SUPPLIER_OF_ID: {
            mergeFilterableSupplierOfId(other.getFilterableSupplierOfId());
            break;
          }
          case NODE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int nodeCase_ = 0;
      private java.lang.Object node_;
      public NodeCase
          getNodeCase() {
        return NodeCase.forNumber(
            nodeCase_);
      }

      public Builder clearNode() {
        nodeCase_ = 0;
        node_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder> filterableSupplierOfIdBuilder_;
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       * @return Whether the filterableSupplierOfId field is set.
       */
      @java.lang.Override
      public boolean hasFilterableSupplierOfId() {
        return nodeCase_ == 1;
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       * @return The filterableSupplierOfId.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId getFilterableSupplierOfId() {
        if (filterableSupplierOfIdBuilder_ == null) {
          if (nodeCase_ == 1) {
            return (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_;
          }
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
        } else {
          if (nodeCase_ == 1) {
            return filterableSupplierOfIdBuilder_.getMessage();
          }
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      public Builder setFilterableSupplierOfId(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId value) {
        if (filterableSupplierOfIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          filterableSupplierOfIdBuilder_.setMessage(value);
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      public Builder setFilterableSupplierOfId(
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder builderForValue) {
        if (filterableSupplierOfIdBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          filterableSupplierOfIdBuilder_.setMessage(builderForValue.build());
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      public Builder mergeFilterableSupplierOfId(io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId value) {
        if (filterableSupplierOfIdBuilder_ == null) {
          if (nodeCase_ == 1 &&
              node_ != io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance()) {
            node_ = io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.newBuilder((io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_)
                .mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          if (nodeCase_ == 1) {
            filterableSupplierOfIdBuilder_.mergeFrom(value);
          }
          filterableSupplierOfIdBuilder_.setMessage(value);
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      public Builder clearFilterableSupplierOfId() {
        if (filterableSupplierOfIdBuilder_ == null) {
          if (nodeCase_ == 1) {
            nodeCase_ = 0;
            node_ = null;
            onChanged();
          }
        } else {
          if (nodeCase_ == 1) {
            nodeCase_ = 0;
            node_ = null;
          }
          filterableSupplierOfIdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder getFilterableSupplierOfIdBuilder() {
        return getFilterableSupplierOfIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder getFilterableSupplierOfIdOrBuilder() {
        if ((nodeCase_ == 1) && (filterableSupplierOfIdBuilder_ != null)) {
          return filterableSupplierOfIdBuilder_.getMessageOrBuilder();
        } else {
          if (nodeCase_ == 1) {
            return (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_;
          }
          return io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.calcite.CalciteNode.FilterableSupplierOfId filterable_supplier_of_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder> 
          getFilterableSupplierOfIdFieldBuilder() {
        if (filterableSupplierOfIdBuilder_ == null) {
          if (!(nodeCase_ == 1)) {
            node_ = io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.getDefaultInstance();
          }
          filterableSupplierOfIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId.Builder, io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfIdOrBuilder>(
                  (io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode.FilterableSupplierOfId) node_,
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        nodeCase_ = 1;
        onChanged();;
        return filterableSupplierOfIdBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataflow.calcite.CalciteNode)
    }

    // @@protoc_insertion_point(class_scope:dataflow.calcite.CalciteNode)
    private static final io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode();
    }

    public static io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalciteNode>
        PARSER = new com.google.protobuf.AbstractParser<CalciteNode>() {
      @java.lang.Override
      public CalciteNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalciteNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalciteNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalciteNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteNodeProto.CalciteNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_calcite_CalciteNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_calcite_CalciteNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032calcite/calcite_node.proto\022\020dataflow.c" +
      "alcite\032\017stream_id.proto\032\035calcite/where_p" +
      "redicate.proto\"\260\002\n\013CalciteNode\022Y\n\031filter" +
      "able_supplier_of_id\030\001 \001(\01324.dataflow.cal" +
      "cite.CalciteNode.FilterableSupplierOfIdH" +
      "\000\032\275\001\n\026FilterableSupplierOfId\022\r\n\005index\030\001 " +
      "\001(\005\022\n\n\002id\030\002 \001(\t\0223\n\tpredicate\030\003 \001(\0132 .dat" +
      "aflow.calcite.WherePredicate\022\027\n\017partitio" +
      "n_index\030\004 \001(\005\022\026\n\016max_partitions\030\005 \001(\005\022\"\n" +
      "\006output\030\006 \001(\0132\022.dataflow.StreamIdB\006\n\004nod" +
      "eB7\n!io.activej.dataflow.proto.calciteB\020" +
      "CalciteNodeProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.activej.dataflow.proto.StreamIdProto.getDescriptor(),
          io.activej.dataflow.proto.calcite.WherePredicateProto.getDescriptor(),
        });
    internal_static_dataflow_calcite_CalciteNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataflow_calcite_CalciteNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_calcite_CalciteNode_descriptor,
        new java.lang.String[] { "FilterableSupplierOfId", "Node", });
    internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor =
      internal_static_dataflow_calcite_CalciteNode_descriptor.getNestedTypes().get(0);
    internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_calcite_CalciteNode_FilterableSupplierOfId_descriptor,
        new java.lang.String[] { "Index", "Id", "Predicate", "PartitionIndex", "MaxPartitions", "Output", });
    io.activej.dataflow.proto.StreamIdProto.getDescriptor();
    io.activej.dataflow.proto.calcite.WherePredicateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
