// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcite/calcite_stream_schema.proto

package io.activej.dataflow.proto.calcite;

public final class CalciteStreamSchemaProto {
  private CalciteStreamSchemaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalciteStreamSchemaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dataflow.calcite.CalciteStreamSchema)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     * @return Whether the recordStreamSchema field is set.
     */
    boolean hasRecordStreamSchema();
    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     * @return The recordStreamSchema.
     */
    io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getRecordStreamSchema();
    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     */
    io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder getRecordStreamSchemaOrBuilder();

    public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.StreamSchemaCase getStreamSchemaCase();
  }
  /**
   * Protobuf type {@code dataflow.calcite.CalciteStreamSchema}
   */
  public static final class CalciteStreamSchema extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dataflow.calcite.CalciteStreamSchema)
      CalciteStreamSchemaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalciteStreamSchema.newBuilder() to construct.
    private CalciteStreamSchema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalciteStreamSchema() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalciteStreamSchema();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalciteStreamSchema(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder subBuilder = null;
              if (streamSchemaCase_ == 1) {
                subBuilder = ((io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_).toBuilder();
              }
              streamSchema_ =
                  input.readMessage(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_);
                streamSchema_ = subBuilder.buildPartial();
              }
              streamSchemaCase_ = 1;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.class, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.Builder.class);
    }

    public interface RecordStreamSchemaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dataflow.calcite.CalciteStreamSchema.RecordStreamSchema)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       * @return Whether the recordScheme field is set.
       */
      boolean hasRecordScheme();
      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       * @return The recordScheme.
       */
      io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme getRecordScheme();
      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       */
      io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder getRecordSchemeOrBuilder();
    }
    /**
     * Protobuf type {@code dataflow.calcite.CalciteStreamSchema.RecordStreamSchema}
     */
    public static final class RecordStreamSchema extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dataflow.calcite.CalciteStreamSchema.RecordStreamSchema)
        RecordStreamSchemaOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RecordStreamSchema.newBuilder() to construct.
      private RecordStreamSchema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RecordStreamSchema() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new RecordStreamSchema();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RecordStreamSchema(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder subBuilder = null;
                if (recordScheme_ != null) {
                  subBuilder = recordScheme_.toBuilder();
                }
                recordScheme_ = input.readMessage(io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(recordScheme_);
                  recordScheme_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.class, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder.class);
      }

      public static final int RECORD_SCHEME_FIELD_NUMBER = 1;
      private io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme recordScheme_;
      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       * @return Whether the recordScheme field is set.
       */
      @java.lang.Override
      public boolean hasRecordScheme() {
        return recordScheme_ != null;
      }
      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       * @return The recordScheme.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme getRecordScheme() {
        return recordScheme_ == null ? io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.getDefaultInstance() : recordScheme_;
      }
      /**
       * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder getRecordSchemeOrBuilder() {
        return getRecordScheme();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (recordScheme_ != null) {
          output.writeMessage(1, getRecordScheme());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (recordScheme_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getRecordScheme());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema)) {
          return super.equals(obj);
        }
        io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema other = (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) obj;

        if (hasRecordScheme() != other.hasRecordScheme()) return false;
        if (hasRecordScheme()) {
          if (!getRecordScheme()
              .equals(other.getRecordScheme())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasRecordScheme()) {
          hash = (37 * hash) + RECORD_SCHEME_FIELD_NUMBER;
          hash = (53 * hash) + getRecordScheme().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dataflow.calcite.CalciteStreamSchema.RecordStreamSchema}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dataflow.calcite.CalciteStreamSchema.RecordStreamSchema)
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.class, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder.class);
        }

        // Construct using io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (recordSchemeBuilder_ == null) {
            recordScheme_ = null;
          } else {
            recordScheme_ = null;
            recordSchemeBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getDefaultInstanceForType() {
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema build() {
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema buildPartial() {
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema result = new io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema(this);
          if (recordSchemeBuilder_ == null) {
            result.recordScheme_ = recordScheme_;
          } else {
            result.recordScheme_ = recordSchemeBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) {
            return mergeFrom((io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema other) {
          if (other == io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance()) return this;
          if (other.hasRecordScheme()) {
            mergeRecordScheme(other.getRecordScheme());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme recordScheme_;
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder> recordSchemeBuilder_;
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         * @return Whether the recordScheme field is set.
         */
        public boolean hasRecordScheme() {
          return recordSchemeBuilder_ != null || recordScheme_ != null;
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         * @return The recordScheme.
         */
        public io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme getRecordScheme() {
          if (recordSchemeBuilder_ == null) {
            return recordScheme_ == null ? io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.getDefaultInstance() : recordScheme_;
          } else {
            return recordSchemeBuilder_.getMessage();
          }
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public Builder setRecordScheme(io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme value) {
          if (recordSchemeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            recordScheme_ = value;
            onChanged();
          } else {
            recordSchemeBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public Builder setRecordScheme(
            io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder builderForValue) {
          if (recordSchemeBuilder_ == null) {
            recordScheme_ = builderForValue.build();
            onChanged();
          } else {
            recordSchemeBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public Builder mergeRecordScheme(io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme value) {
          if (recordSchemeBuilder_ == null) {
            if (recordScheme_ != null) {
              recordScheme_ =
                io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.newBuilder(recordScheme_).mergeFrom(value).buildPartial();
            } else {
              recordScheme_ = value;
            }
            onChanged();
          } else {
            recordSchemeBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public Builder clearRecordScheme() {
          if (recordSchemeBuilder_ == null) {
            recordScheme_ = null;
            onChanged();
          } else {
            recordScheme_ = null;
            recordSchemeBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder getRecordSchemeBuilder() {
          
          onChanged();
          return getRecordSchemeFieldBuilder().getBuilder();
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        public io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder getRecordSchemeOrBuilder() {
          if (recordSchemeBuilder_ != null) {
            return recordSchemeBuilder_.getMessageOrBuilder();
          } else {
            return recordScheme_ == null ?
                io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.getDefaultInstance() : recordScheme_;
          }
        }
        /**
         * <code>.dataflow.calcite.RecordScheme record_scheme = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder> 
            getRecordSchemeFieldBuilder() {
          if (recordSchemeBuilder_ == null) {
            recordSchemeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordScheme.Builder, io.activej.dataflow.proto.calcite.RecordSchemeProto.RecordSchemeOrBuilder>(
                    getRecordScheme(),
                    getParentForChildren(),
                    isClean());
            recordScheme_ = null;
          }
          return recordSchemeBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dataflow.calcite.CalciteStreamSchema.RecordStreamSchema)
      }

      // @@protoc_insertion_point(class_scope:dataflow.calcite.CalciteStreamSchema.RecordStreamSchema)
      private static final io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema();
      }

      public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RecordStreamSchema>
          PARSER = new com.google.protobuf.AbstractParser<RecordStreamSchema>() {
        @java.lang.Override
        public RecordStreamSchema parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RecordStreamSchema(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RecordStreamSchema> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<RecordStreamSchema> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int streamSchemaCase_ = 0;
    private java.lang.Object streamSchema_;
    public enum StreamSchemaCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      RECORD_STREAM_SCHEMA(1),
      STREAMSCHEMA_NOT_SET(0);
      private final int value;
      private StreamSchemaCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StreamSchemaCase valueOf(int value) {
        return forNumber(value);
      }

      public static StreamSchemaCase forNumber(int value) {
        switch (value) {
          case 1: return RECORD_STREAM_SCHEMA;
          case 0: return STREAMSCHEMA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public StreamSchemaCase
    getStreamSchemaCase() {
      return StreamSchemaCase.forNumber(
          streamSchemaCase_);
    }

    public static final int RECORD_STREAM_SCHEMA_FIELD_NUMBER = 1;
    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     * @return Whether the recordStreamSchema field is set.
     */
    @java.lang.Override
    public boolean hasRecordStreamSchema() {
      return streamSchemaCase_ == 1;
    }
    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     * @return The recordStreamSchema.
     */
    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getRecordStreamSchema() {
      if (streamSchemaCase_ == 1) {
         return (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_;
      }
      return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
    }
    /**
     * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
     */
    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder getRecordStreamSchemaOrBuilder() {
      if (streamSchemaCase_ == 1) {
         return (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_;
      }
      return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (streamSchemaCase_ == 1) {
        output.writeMessage(1, (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (streamSchemaCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema)) {
        return super.equals(obj);
      }
      io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema other = (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema) obj;

      if (!getStreamSchemaCase().equals(other.getStreamSchemaCase())) return false;
      switch (streamSchemaCase_) {
        case 1:
          if (!getRecordStreamSchema()
              .equals(other.getRecordStreamSchema())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (streamSchemaCase_) {
        case 1:
          hash = (37 * hash) + RECORD_STREAM_SCHEMA_FIELD_NUMBER;
          hash = (53 * hash) + getRecordStreamSchema().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dataflow.calcite.CalciteStreamSchema}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dataflow.calcite.CalciteStreamSchema)
        io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchemaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.class, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.Builder.class);
      }

      // Construct using io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streamSchemaCase_ = 0;
        streamSchema_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.internal_static_dataflow_calcite_CalciteStreamSchema_descriptor;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema getDefaultInstanceForType() {
        return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.getDefaultInstance();
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema build() {
        io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema buildPartial() {
        io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema result = new io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema(this);
        if (streamSchemaCase_ == 1) {
          if (recordStreamSchemaBuilder_ == null) {
            result.streamSchema_ = streamSchema_;
          } else {
            result.streamSchema_ = recordStreamSchemaBuilder_.build();
          }
        }
        result.streamSchemaCase_ = streamSchemaCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema) {
          return mergeFrom((io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema other) {
        if (other == io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.getDefaultInstance()) return this;
        switch (other.getStreamSchemaCase()) {
          case RECORD_STREAM_SCHEMA: {
            mergeRecordStreamSchema(other.getRecordStreamSchema());
            break;
          }
          case STREAMSCHEMA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int streamSchemaCase_ = 0;
      private java.lang.Object streamSchema_;
      public StreamSchemaCase
          getStreamSchemaCase() {
        return StreamSchemaCase.forNumber(
            streamSchemaCase_);
      }

      public Builder clearStreamSchema() {
        streamSchemaCase_ = 0;
        streamSchema_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder> recordStreamSchemaBuilder_;
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       * @return Whether the recordStreamSchema field is set.
       */
      @java.lang.Override
      public boolean hasRecordStreamSchema() {
        return streamSchemaCase_ == 1;
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       * @return The recordStreamSchema.
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema getRecordStreamSchema() {
        if (recordStreamSchemaBuilder_ == null) {
          if (streamSchemaCase_ == 1) {
            return (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_;
          }
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
        } else {
          if (streamSchemaCase_ == 1) {
            return recordStreamSchemaBuilder_.getMessage();
          }
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      public Builder setRecordStreamSchema(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema value) {
        if (recordStreamSchemaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          streamSchema_ = value;
          onChanged();
        } else {
          recordStreamSchemaBuilder_.setMessage(value);
        }
        streamSchemaCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      public Builder setRecordStreamSchema(
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder builderForValue) {
        if (recordStreamSchemaBuilder_ == null) {
          streamSchema_ = builderForValue.build();
          onChanged();
        } else {
          recordStreamSchemaBuilder_.setMessage(builderForValue.build());
        }
        streamSchemaCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      public Builder mergeRecordStreamSchema(io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema value) {
        if (recordStreamSchemaBuilder_ == null) {
          if (streamSchemaCase_ == 1 &&
              streamSchema_ != io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance()) {
            streamSchema_ = io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.newBuilder((io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_)
                .mergeFrom(value).buildPartial();
          } else {
            streamSchema_ = value;
          }
          onChanged();
        } else {
          if (streamSchemaCase_ == 1) {
            recordStreamSchemaBuilder_.mergeFrom(value);
          }
          recordStreamSchemaBuilder_.setMessage(value);
        }
        streamSchemaCase_ = 1;
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      public Builder clearRecordStreamSchema() {
        if (recordStreamSchemaBuilder_ == null) {
          if (streamSchemaCase_ == 1) {
            streamSchemaCase_ = 0;
            streamSchema_ = null;
            onChanged();
          }
        } else {
          if (streamSchemaCase_ == 1) {
            streamSchemaCase_ = 0;
            streamSchema_ = null;
          }
          recordStreamSchemaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder getRecordStreamSchemaBuilder() {
        return getRecordStreamSchemaFieldBuilder().getBuilder();
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      @java.lang.Override
      public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder getRecordStreamSchemaOrBuilder() {
        if ((streamSchemaCase_ == 1) && (recordStreamSchemaBuilder_ != null)) {
          return recordStreamSchemaBuilder_.getMessageOrBuilder();
        } else {
          if (streamSchemaCase_ == 1) {
            return (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_;
          }
          return io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
        }
      }
      /**
       * <code>.dataflow.calcite.CalciteStreamSchema.RecordStreamSchema record_stream_schema = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder> 
          getRecordStreamSchemaFieldBuilder() {
        if (recordStreamSchemaBuilder_ == null) {
          if (!(streamSchemaCase_ == 1)) {
            streamSchema_ = io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.getDefaultInstance();
          }
          recordStreamSchemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema.Builder, io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchemaOrBuilder>(
                  (io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema.RecordStreamSchema) streamSchema_,
                  getParentForChildren(),
                  isClean());
          streamSchema_ = null;
        }
        streamSchemaCase_ = 1;
        onChanged();;
        return recordStreamSchemaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dataflow.calcite.CalciteStreamSchema)
    }

    // @@protoc_insertion_point(class_scope:dataflow.calcite.CalciteStreamSchema)
    private static final io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema();
    }

    public static io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalciteStreamSchema>
        PARSER = new com.google.protobuf.AbstractParser<CalciteStreamSchema>() {
      @java.lang.Override
      public CalciteStreamSchema parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalciteStreamSchema(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalciteStreamSchema> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalciteStreamSchema> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.activej.dataflow.proto.calcite.CalciteStreamSchemaProto.CalciteStreamSchema getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_calcite_CalciteStreamSchema_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_calcite_CalciteStreamSchema_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#calcite/calcite_stream_schema.proto\022\020d" +
      "ataflow.calcite\032\033calcite/record_scheme.p" +
      "roto\"\315\001\n\023CalciteStreamSchema\022X\n\024record_s" +
      "tream_schema\030\001 \001(\01328.dataflow.calcite.Ca" +
      "lciteStreamSchema.RecordStreamSchemaH\000\032K" +
      "\n\022RecordStreamSchema\0225\n\rrecord_scheme\030\001 " +
      "\001(\0132\036.dataflow.calcite.RecordSchemeB\017\n\rs" +
      "tream_schemaB?\n!io.activej.dataflow.prot" +
      "o.calciteB\030CalciteStreamSchemaProtoP\000b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.activej.dataflow.proto.calcite.RecordSchemeProto.getDescriptor(),
        });
    internal_static_dataflow_calcite_CalciteStreamSchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dataflow_calcite_CalciteStreamSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_calcite_CalciteStreamSchema_descriptor,
        new java.lang.String[] { "RecordStreamSchema", "StreamSchema", });
    internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor =
      internal_static_dataflow_calcite_CalciteStreamSchema_descriptor.getNestedTypes().get(0);
    internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dataflow_calcite_CalciteStreamSchema_RecordStreamSchema_descriptor,
        new java.lang.String[] { "RecordScheme", });
    io.activej.dataflow.proto.calcite.RecordSchemeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
